### ISSUE TITLE
Backport to older mc versions

### ISSUE THREAD

**Issue by thecatcore** [Mari023/pressalttomeow#2]
Like 1.18.x or 1.17.x or even 1.16.x

**Comment by Mari023** [comment]
should be doable
potentially it might also just work with other versions (if you use a dependency override / edit the fabric.mod.json in the .jar)

**Comment by Mari023** [comment]
it works on 1.18.2
it also works on 1.16.5 if you use java 17

**Comment by Mari023** [comment]
I'll make a release which works with these versions out of the box soon
